name: Push Files to Repository

on:
  workflow_dispatch:

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUBACTION }}

    - name: Add Files
      run: |
        exit -1
        echo God is great >> God.txt
        cat God.txt

    - name: Commit and Push
      run: |
        git config user.email "dhanapathi.marepalli@gmail.com"
        git config user.name "Dhana"
        git add .
        git commit -m "Add files"
        git push origin HEAD
